//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleClinicaEstetica
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgendarCliente
    {
        public int IdAgendamento { get; set; }
        public string Nome_do_Cliente { get; set; }
        public string Tipo_de_Procedimento { get; set; }
        public System.DateTime Data_da_Realizacao { get; set; }
        public decimal Valor_do_procedimento { get; set; }
    }
}
